import Navbar from './Navbar'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Head from 'next/head';
import Footer from './Footer';
const inter = Inter({ subsets: ['latin'] })
const About = () => {
    return (
        <>
      <Head>
        <title>Nextjs-Ecommerce-Project/about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
     <main className={`${styles.main} ${inter.className}`}> 
        <Navbar></Navbar>
        <div>
            <h1 className='text-5xl font-bold text-center'>This is About</h1>
            <Footer></Footer>
        </div>
       </main>
       </>
    );
};

export default About;